# web服务端口号
server.port: 9000

server:
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true

management:
  endpoints:
    web:
      base-path: /monitor
      path-mapping:
        health: /alive
  health:
    defaults:
      enabled: false

spring:
  profiles:
    active: @mvn.active@
  mail:
    username: 1016496469@qq.com
    password: ckmgyeoqaylobbhd
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  application:
    name: com.wxjj
  lifecycle:
    timeout-per-shutdown-phase: 50s

redis-config:
  host: 127.0.0.1
  port: 6379
  password:
  database: 3
  minIdle: 10
  maxIdle: 10
  maxTotal: 20

---
spring:
  config:
    activate:
      on-profile: dev

db-config:
  - name: warehouse
    basePackages: com.wx.dao.warehouse.mapper
    useGeneratedKeys: true
    defaultStatementTimeout: 10
    master:
      url: 127.0.0.1:3306/warehouse
      username: root
      password:
      minIdle: 10
      initialSize: 10
      maxActive: 20
    slave:
      url: 127.0.0.1:3306/warehouse
      username: warehouse_read
      password: Ab123456
      minIdle: 10
      initialSize: 10
      maxActive: 20

#日志配置文件位置
logging:
  config: classpath:logback-dev.xml
---
spring:
  config:
    activate:
      on-profile: stag

db-config:
  - name: warehouse
    basePackages: com.wx.dao.warehouse.mapper
    useGeneratedKeys: true
    defaultStatementTimeout: 10
    master:
      url: 127.0.0.1:3306/warehouse
      username: root
      password: Flzx@3qc
      minIdle: 10
      initialSize: 10
      maxActive: 20
    slave:
      url: 127.0.0.1:3306/warehouse
      username: warehouse_read
      password: Flzx@3qc
      minIdle: 10
      initialSize: 10
      maxActive: 20

#日志配置文件位置
logging:
  config: classpath:logback-stag.xml
---

