@startuml
'uml学习'

title uml学习

actor A #red
participant B as "名字非常\n长的服务" #99FF99
database C #yellow

autonumber 1

A -> B: 发起请求

B -> B: 参数校验

opt 参数校验失败
B -> A: 参数校验未通过
end

B -> C: 存储数据
return 存储结果

B -> A: 请求响应

autonumber stop

A -[#red]> A: 阅读结果\n反思流程

@enduml
