@startuml
'uml学习'

title uml学习

actor A #red
participant B as "名字非常\n长的服务" #99FF99
database C #yellow

autonumber 1

A -> B: 发起请求
B --> A: 请求响应

B -> C: 存储数据
B <-- C: 存储结果

autonumber stop

A-[#red]>A: 阅读结果\n反思流程

@enduml
