@startuml

hide empty description

state 退款成功 #pink

state 已取消 #pink

[*] -right-> 初始化 : 用户提交
初始化 : 收单后待处理数据

初始化 -down-> 支付中 : 发起支付

支付中 -down-> 支付成功 : 支付回调成功

支付成功 -down-> 退款中 : 申请退款
退款中 -down-> 退款失败 : 支付返回失败
退款中 -down-> 退款成功 : 支付返回成功
退款失败 -right-> 退款成功 : 人工介入
退款成功 -right-> [*]

支付中 -down-> 支付失败 : 支付回调失败

支付失败 -up-> 支付中 : 截止时间内重试
支付失败 -down-> [*] : 超出截止时间

支付中 -down-> 已取消 : 关闭支付
已取消 -down-> [*]

note right of 支付失败 : 没有到达截止时间的可以重试

@enduml
